version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=pgname
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local